global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert-rules/*.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "winu-bot-signal-api"
    static_configs:
      - targets: ["api:8001"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["winu-bot-signal-postgres-exporter:9187"]
    scrape_interval: 30s

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["winu-bot-signal-redis-exporter:9121"]
    scrape_interval: 30s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["winu-bot-signal-node-exporter:9100"]
    scrape_interval: 30s

  - job_name: "winu-bot-metrics"
    static_configs:
      - targets: ["winu-bot-signal-metrics-exporter:8002"]
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093




